### ISSUE TITLE
Error during import

### ISSUE THREAD

**Issue by ratanou** [persistentsystems/adcms#7]
Hello, 
Attempting to import VMs, I receive this message : "Validation exception occurred : Insufficient space for core counts in destination subscription". 

I have one subscription with 13 VMs and I would like to copy only 5 VMs to another empty subscription.

I tried to create one VMs in my empty subscription and copy it to another empty subscription and it works fine.

I think that I have this problem because I have to many VMs in my subscription.

Question : Is there any solution to selected only VMs, cloudservice etc.. that I want to "export/import" ? (without editing the .json ?)

Thank you for your answer.

Ratana.

**Comment by itsmaryann** [comment]
Hi Ratana,

Selection of VMs can be done only by editing the JSON. You may refer to section "Choose resources to migrate" in the User Guide for more details.

Thanks.

**Comment by ratanou** [comment]
Thank you for your answer
